server:
  port: 8080
spring:
 cloud.stream:
  function.definition: userProcessor;userService
  bindings:
    userProcessor-in-0:
      destination: userMessage4
    userProcessor-out-0:
      destination: user4
    userService-in-0:
      destination: user4
  kafka:
    streams:
      binder:
        configuration:
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        deserializationExceptionHandler: logAndContinue
        functions:
          userService:
            applicationId: group-id
          userProcessor:
            applicationId: userprocessor-consumer-group-id
          bindings:
            userProcessor-in-0.consumer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            userProcessor-out-0.producer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            userService-in-0.consumer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            userService-in-0.producer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    schema:
      avro:
        dynamic-schema-generation-enabled: true
spring.kafka:
  bootstrap-servers: localhost:9092
  properties:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    schema:
      registry:
        url: http://localhost:8081
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
  consumer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
